---
- name: Check podman package installation
  shell: dpkg -l | grep podman | awk '{print $2}'
  register: podman_install

- name: Install podman package
  shell: |
    echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /' | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | apt-key add -
    apt-get update
    echo 'N\nN' > tmp_podman
    apt-get install -y podman < tmp_podman
  when: podman_install.stdout == ""

- name: Delete tmp file
  file:
    path: "tmp_podman"
    state: absent

- name: Add registries.conf
  shell: |
    cat <<EOF > /etc/containers/registries.conf.d/10-harbor.{{ ingress_nginx_public_ip }}.nip.io.conf
    [[registry]]
    prefix = "harbor.{{ ingress_nginx_public_ip }}.nip.io"
    insecure = true
    blocked = false
    location = "harbor.{{ ingress_nginx_public_ip }}.nip.io"
    EOF

- name: Restart podman service
  shell: systemctl restart podman
