---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Download terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_linux_amd64.zip"
    dest: "{{ home_dir_path.stdout }}/terraform_1.3.4_linux_amd64.zip"

- name: Unarchive terraform
  unarchive:
    src: "{{ home_dir_path }}/terraform_1.3.4_linux_amd64.zip"
    dest: "/usr/local/bin"
    mode: "0755"

- name: Delete terraform zip
  file:
    path: "{{ home_dir_path.stdout }}/terraform_1.3.4_linux_amd64.zip"
    state: absent
