---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Copy vars file
  become: false
  copy:
    src: "{{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars{{ groups['kube_control_plane'].index(inventory_hostname)|int + 1|int }}.sh"
    dest: "{{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh"

- name: Copy key file
  become: false
  copy:
    src: "{{ home_dir_path.stdout }}/.ssh/id_rsa"
    dest: "{{ home_dir_path.stdout }}/.ssh/id_rsa"

- name: Chmod key file
  become: false
  file:
    path: "{{ home_dir_path.stdout }}/.ssh/id_rsa"
    mode: "0600"
