---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Download container platform deployment
  become: false
  git:
    repo: https://gitlab.10.100.0.138.nip.io/container-platform-v2/cp-deployment.git
    dest: "{{ home_dir_path.stdout }}/cp-deployment/"
