---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Install istio-cni
  become: false
  shell: |
    helm repo add istio https://istio-release.storage.googleapis.com/charts
    helm install istio-cni istio/cni -n istio-system

- name: Get istio-sidecar-injector configmap .data.values
  become: false
  shell: |
    kubectl get configmap istio-sidecar-injector -n istio-system -o json | jq .data.values | sed -E 's/\\\"istio_cni\\\"\: \{\\n    \\\"enabled\\\"\: false/\\\"istio_cni\\\"\: \{\\n    \\\"enabled\\\"\: true/g'
  register: configmap_value

- name: Modify istio configmap
  become: false
  shell: |
    kubectl patch configmap istio-sidecar-injector --patch '{"data": { "values": {{ configmap_value.stdout }} }}' -n istio-system
